package com.svi.tictactoewebservice.service.impl;

import com.svi.tictactoewebservice.dto.request.RoomRequest;
import com.svi.tictactoewebservice.dto.response.RoomResponse;
import com.svi.tictactoewebservice.model.Room;
import com.svi.tictactoewebservice.repository.RoomRepository;
import com.svi.tictactoewebservice.service.RoomService;
import com.svi.tictactoewebservice.validator.IdValidator;

import java.io.IOException;


public class RoomServiceImpl implements RoomService {

    private final RoomRepository roomRepository = new RoomRepository();
    private final IdValidator idValidator = new IdValidator();

    @Override
    public RoomResponse createRoom(RoomRequest request) throws IOException {

        idValidator.validateRoomId(request.getRoomCode());

        Room room = new Room();
        room.setRoomCode(request.getRoomCode());
        roomRepository.createRoom(room);

        return new RoomResponse(room.getRoomCode(),room.getGameIds());
    }

    @Override
    public RoomResponse getRoom(String roomCode) throws IOException {

        idValidator.validateRoomId(roomCode);
        Room room = roomRepository.findRoom(roomCode);

        if (room == null){
            return null;
        }

        return new RoomResponse(room.getRoomCode(),room.getGameIds());
    }

    @Override
    public void addGameToRoom(String roomCode, String gameId) throws IOException {
        idValidator.validateRoomId(roomCode); // Game ID is not validated here because it is generated by the backend as a UUID.
        roomRepository.addGameToRoom(roomCode, gameId);
    }
}