package com.svi.tictactoewebservice.service.impl;

import com.svi.tictactoewebservice.dto.request.RoomRequest;
import com.svi.tictactoewebservice.dto.response.ApiResponse;
import com.svi.tictactoewebservice.dto.response.RoomResponse;
import com.svi.tictactoewebservice.model.Room;
import com.svi.tictactoewebservice.repository.RoomRepository;
import com.svi.tictactoewebservice.service.RoomService;
import com.svi.tictactoewebservice.validator.IdValidator;
import com.svi.tictactoewebservice.repository.CassandraRepository;

import java.io.IOException;


public class RoomServiceImpl implements RoomService {

    private final RoomRepository roomRepository = new RoomRepository();
    private final CassandraRepository cassandraRepository;

    public RoomServiceImpl(CassandraRepository cassandraRepository) {
        this.cassandraRepository = cassandraRepository;
    }

    @Override
    public ApiResponse createRoom(RoomRequest request) throws IOException {

        //for old file-base repository
        //Room room = new Room();
        //room.setRoomCode(request.getRoomCode());
        //roomRepository.createRoom(room);
        cassandraRepository.createRoom(request.getRoomCode());

        return new ApiResponse("Room record created.");
    }

    @Override
    public RoomResponse getRoom(String roomCode) throws IOException {

        //Room room = roomRepository.findRoom(roomCode);
        Room room = cassandraRepository.findRoom(roomCode);

        if (room == null){
            return null;
        }

        return new RoomResponse(room.getRoomCode(),room.getGameIds());
    }

    @Override
    public void addGameToRoom(String roomCode, String gameId) throws IOException {
        // Game ID is not validated here because it is generated by the backend as a UUID.
        //roomRepository.addGameToRoom(roomCode, gameId);
        cassandraRepository.addGameToRoom(roomCode, gameId);
    }
}