package com.svi.tictactoewebservice.service.impl;

import com.svi.tictactoewebservice.connection.CassandraConnection;
import com.svi.tictactoewebservice.dto.request.RoomRequest;
import com.svi.tictactoewebservice.dto.response.ApiResponse;
import com.svi.tictactoewebservice.dto.response.RoomResponse;
import com.svi.tictactoewebservice.model.Room;
import com.svi.tictactoewebservice.repository.RoomRepository;
import com.svi.tictactoewebservice.service.RoomService;
import com.svi.tictactoewebservice.validator.IdValidator;
import com.svi.tictactoewebservice.repository.CassandraRepository;

import java.io.IOException;


public class RoomServiceImpl implements RoomService {

    private final CassandraRepository cassandraRepository = new CassandraRepository(CassandraConnection.getInstance().getSession());
    private final RoomRepository roomRepository = new RoomRepository();



    @Override
    public RoomResponse getRoom(String roomCode) throws IOException {

        //Room room = roomRepository.findRoom(roomCode);
        Room room = cassandraRepository.findRoom(roomCode);

        if (room == null){
            return null;
        }

        return new RoomResponse(room.getRoomCode(),room.getGameIds());
    }

    @Override
    public void addGameToRoom(String roomCode, String gameId) throws IOException {
        // Game ID is not validated here because it is generated by the backend as a UUID.
        //roomRepository.addGameToRoom(roomCode, gameId);
        cassandraRepository.addGameToRoom(roomCode, gameId);
    }
}