RECORDS_DIR=C:/Users/glen.annang/Documents/tic-tac-toe-webservices/tic-tac-toe-webservices/records
PLAYER_DIR=players
GAME_DIR=games
ROOM_DIR=rooms
FRONTEND_URL=http://127.0.0.1:5500

; CASSANDRA_IP=172.31.9.25
; CASSANDRA_PORT=9042
; CASSANDRA_KEYSPACE=batch1_2026_trainees

; CASSANDRA_IP=127.0.0.1
; CASSANDRA_PORT=9042
; CASSANDRA_KEYSPACE=cassandra_activity;